version: '3.8'

services:
  fiber_storage:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiber_storage
    ports:
      - "5432:5432"
    volumes:
      - fiber_storage_volume:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8000
    ports:
    - "8000:8000"
    volumes:
    - ./servers.json:/pgadmin4/servers.json

volumes:
  fiber_storage_volume:
  db_volume:
